(load "dirt.scm")
(emit-binary
  '((push 3)
    (push 800)
    (mov (%ecx) %ebx)
    (mov %ebx (%ecx))
    (mov %ebx (-3 . %ecx))
    (mov %ebx (40000 . %ecx))
    (push %ecx)
    (mov 3 %eax)
    (mov %eax %ebx)
    (label TEST)
    (cmp %eax 3)
    (add %eax 4)
    (sub %eax 40000)
    (cmp %eax %ebx)
    (je TEST)
    (label FOO)
    (jne FOO)
    (call TEST)
    (pop %eax)
    (jmp BLAH)
    (or %eax 4)
    (label BLAH)
    (shl %eax 4)
    (shr %eax 4)
    (imul %eax %ebx)
    (and %ebx 4)
    (ret)) "test")
(system "objdump -D -b binary -mi386 test")

